# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\Coding\Python\3Knights\mainwindow_ui.ui'
#
# Created: Mon Dec  8 01:48:21 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(517, 431)
        self.lab2 = QtWidgets.QLabel(Form)
        self.lab2.setGeometry(QtCore.QRect(60, 70, 46, 13))
        self.lab2.setObjectName("lab2")
        self.new_game = QtWidgets.QPushButton(Form)
        self.new_game.setGeometry(QtCore.QRect(200, 20, 75, 23))
        self.new_game.setObjectName("new_game")
        self.bot_path2 = QtWidgets.QLineEdit(Form)
        self.bot_path2.setGeometry(QtCore.QRect(270, 140, 113, 20))
        self.bot_path2.setObjectName("bot_path2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(220, 0, 41, 16))
        self.label.setObjectName("label")
        self.start = QtWidgets.QPushButton(Form)
        self.start.setGeometry(QtCore.QRect(200, 180, 75, 23))
        self.start.setObjectName("start")
        self.browse2 = QtWidgets.QPushButton(Form)
        self.browse2.setGeometry(QtCore.QRect(400, 140, 75, 23))
        self.browse2.setObjectName("browse2")
        self.load_game = QtWidgets.QPushButton(Form)
        self.load_game.setGeometry(QtCore.QRect(200, 210, 75, 23))
        self.load_game.setObjectName("load_game")
        self.bot_path1 = QtWidgets.QLineEdit(Form)
        self.bot_path1.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.bot_path1.setObjectName("bot_path1")
        self.browse1 = QtWidgets.QPushButton(Form)
        self.browse1.setGeometry(QtCore.QRect(130, 140, 75, 23))
        self.browse1.setObjectName("browse1")
        self.load_path = QtWidgets.QLineEdit(Form)
        self.load_path.setGeometry(QtCore.QRect(180, 270, 113, 20))
        self.load_path.setObjectName("load_path")
        self.load_game2 = QtWidgets.QPushButton(Form)
        self.load_game2.setGeometry(QtCore.QRect(200, 240, 75, 23))
        self.load_game2.setObjectName("load_game2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 120, 80))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.rb1 = QtWidgets.QRadioButton(self.groupBox)
        self.rb1.setGeometry(QtCore.QRect(10, 40, 51, 17))
        self.rb1.setObjectName("rb1")
        self.rb2 = QtWidgets.QRadioButton(self.groupBox)
        self.rb2.setGeometry(QtCore.QRect(60, 40, 82, 17))
        self.rb2.setObjectName("rb2")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 60, 191, 80))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.rb3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb3.setGeometry(QtCore.QRect(0, 30, 82, 17))
        self.rb3.setObjectName("rb3")
        self.rb4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb4.setGeometry(QtCore.QRect(100, 30, 82, 17))
        self.rb4.setObjectName("rb4")
        self.lab3 = QtWidgets.QLabel(self.groupBox_2)
        self.lab3.setGeometry(QtCore.QRect(70, 10, 46, 13))
        self.lab3.setObjectName("lab3")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(170, 330, 241, 56))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.back1 = QtWidgets.QPushButton(self.widget)
        self.back1.setObjectName("back1")
        self.gridLayout.addWidget(self.back1, 1, 1, 1, 1)
        self.rules = QtWidgets.QPushButton(self.widget)
        self.rules.setObjectName("rules")
        self.gridLayout.addWidget(self.rules, 0, 1, 1, 1)
        self.back2 = QtWidgets.QPushButton(self.widget)
        self.back2.setObjectName("back2")
        self.gridLayout.addWidget(self.back2, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.browse3 = QtWidgets.QPushButton(self.widget)
        self.browse3.setObjectName("browse3")
        self.horizontalLayout.addWidget(self.browse3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lab2.setText(_translate("Form", "Player 1"))
        self.new_game.setText(_translate("Form", "New Game"))
        self.label.setText(_translate("Form", "3Knights"))
        self.start.setText(_translate("Form", "Start"))
        self.browse2.setText(_translate("Form", "Browse"))
        self.load_game.setText(_translate("Form", "Load Game"))
        self.browse1.setText(_translate("Form", "Browse"))
        self.load_game2.setText(_translate("Form", "Load Game"))
        self.rb1.setText(_translate("Form", "Bot"))
        self.rb2.setText(_translate("Form", "Human"))
        self.rb3.setText(_translate("Form", "Bot"))
        self.rb4.setText(_translate("Form", "Human"))
        self.lab3.setText(_translate("Form", "Player 2"))
        self.back1.setText(_translate("Form", "Back"))
        self.rules.setText(_translate("Form", "Rules"))
        self.back2.setText(_translate("Form", "Back"))
        self.browse3.setText(_translate("Form", "Browse"))

