# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_ui.ui'
#
# Created: Sun Feb  7 16:31:54 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(498, 373)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.new_game = QtWidgets.QPushButton(Form)
        self.new_game.setObjectName("new_game")
        self.horizontalLayout_6.addWidget(self.new_game)
        self.onlineGameButton = QtWidgets.QPushButton(Form)
        self.onlineGameButton.setObjectName("onlineGameButton")
        self.horizontalLayout_6.addWidget(self.onlineGameButton)
        self.start = QtWidgets.QPushButton(Form)
        self.start.setObjectName("start")
        self.horizontalLayout_6.addWidget(self.start)
        self.back1 = QtWidgets.QPushButton(Form)
        self.back1.setObjectName("back1")
        self.horizontalLayout_6.addWidget(self.back1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lab2 = QtWidgets.QLabel(self.groupBox)
        self.lab2.setStyleSheet("background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 176, 176, 167), stop:0.0909091 rgba(0, 255, 191, 51), stop:0.1 rgba(0, 255, 234, 255), stop:0.409091 rgba(1, 255, 223, 92), stop:0.6 rgba(180, 255, 240, 84), stop:1 rgba(76, 218, 255, 205))")
        self.lab2.setObjectName("lab2")
        self.verticalLayout_3.addWidget(self.lab2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rb1 = QtWidgets.QRadioButton(self.groupBox)
        self.rb1.setObjectName("rb1")
        self.horizontalLayout_3.addWidget(self.rb1)
        self.rb2 = QtWidgets.QRadioButton(self.groupBox)
        self.rb2.setObjectName("rb2")
        self.horizontalLayout_3.addWidget(self.rb2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bot_path1 = QtWidgets.QLineEdit(Form)
        self.bot_path1.setObjectName("bot_path1")
        self.horizontalLayout_4.addWidget(self.bot_path1)
        self.browse1 = QtWidgets.QPushButton(Form)
        self.browse1.setObjectName("browse1")
        self.horizontalLayout_4.addWidget(self.browse1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lab3 = QtWidgets.QLabel(self.groupBox_2)
        self.lab3.setStyleSheet("")
        self.lab3.setObjectName("lab3")
        self.verticalLayout.addWidget(self.lab3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rb3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb3.setObjectName("rb3")
        self.horizontalLayout_2.addWidget(self.rb3)
        self.rb4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb4.setObjectName("rb4")
        self.horizontalLayout_2.addWidget(self.rb4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bot_path2 = QtWidgets.QLineEdit(Form)
        self.bot_path2.setObjectName("bot_path2")
        self.horizontalLayout.addWidget(self.bot_path2)
        self.browse2 = QtWidgets.QPushButton(Form)
        self.browse2.setObjectName("browse2")
        self.horizontalLayout.addWidget(self.browse2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.load_game = QtWidgets.QPushButton(Form)
        self.load_game.setObjectName("load_game")
        self.verticalLayout_5.addWidget(self.load_game)
        self.load_game2 = QtWidgets.QPushButton(Form)
        self.load_game2.setObjectName("load_game2")
        self.verticalLayout_5.addWidget(self.load_game2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.back2 = QtWidgets.QPushButton(Form)
        self.back2.setObjectName("back2")
        self.horizontalLayout_8.addWidget(self.back2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.load_path = QtWidgets.QLineEdit(Form)
        self.load_path.setObjectName("load_path")
        self.horizontalLayout_7.addWidget(self.load_path)
        self.browse3 = QtWidgets.QPushButton(Form)
        self.browse3.setObjectName("browse3")
        self.horizontalLayout_7.addWidget(self.browse3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.rules = QtWidgets.QPushButton(Form)
        self.rules.setObjectName("rules")
        self.horizontalLayout_9.addWidget(self.rules)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.new_game.setText(_translate("Form", "New Game"))
        self.onlineGameButton.setText(_translate("Form", "Online Game"))
        self.start.setText(_translate("Form", "Start"))
        self.back1.setText(_translate("Form", "Back"))
        self.lab2.setText(_translate("Form", "Player 1"))
        self.rb1.setText(_translate("Form", "Bot"))
        self.rb2.setText(_translate("Form", "Human"))
        self.browse1.setText(_translate("Form", "Browse"))
        self.lab3.setText(_translate("Form", "Player 2"))
        self.rb3.setText(_translate("Form", "Bot"))
        self.rb4.setText(_translate("Form", "Human"))
        self.browse2.setText(_translate("Form", "Browse"))
        self.load_game.setText(_translate("Form", "Load Game"))
        self.load_game2.setText(_translate("Form", "Load Game"))
        self.back2.setText(_translate("Form", "Back"))
        self.browse3.setText(_translate("Form", "Browse"))
        self.rules.setText(_translate("Form", "Rules"))

